# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 18:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180228_1352'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
